// <auto-generated />
using CustomerWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerWebApp.Migrations
{
    [DbContext(typeof(CustomerWebAppContext))]
    [Migration("20221110143527_InternetBankingLoginCreds")]
    partial class InternetBankingLoginCreds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerWebApp.Models.InternetBankingLoginCreds", b =>
                {
                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialNumber"), 1L, 1);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("InternetBankingId")
                        .HasColumnType("int");

                    b.Property<int>("InternetBankingPassword")
                        .HasColumnType("int");

                    b.HasKey("SerialNumber");

                    b.ToTable("InternetBankingLoginCreds");
                });
#pragma warning restore 612, 618
        }
    }
}
